# Generated by Django 3.1.3 on 2020-11-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
