# Generated by Django 3.1.3 on 2020-11-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traction_app', '0001_initial'),
        ('users', '0003_auto_20201117_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(to='traction_app.Item'),
        ),
    ]
