# Generated by Django 3.1.3 on 2020-11-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='items',
            new_name='tracked_items',
        ),
    ]
